name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build workspace
      run: cargo build --workspace --all-targets

    - name: Run ort-test
      run: cargo run -p ort-test
