name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    permissions:
      contents: write    # Allows creating tags, commits, and pushing code if needed
      deployments: write    # Allows creating and updating GitHub releases
      actions: write     # Allows uploading workflow artifacts and interacting with workflow artifacts
      packages: write
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            linux-override: false
          - os: macos-13
            linux-override: false
          - os: macos-14
            linux-override: false
          - os: windows-latest
            linux-override: false
          # - os: ubuntu-latest  # Extra Ubuntu build for ARM support
          #   linux-override: true
    runs-on: ${{ matrix.platform.os }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build workspace
      run: cargo build --workspace --all-targets

    - name: Run ort-test
      run: cargo run -p ort-test
